### ISSUE TITLE
Optimizing code

### ISSUE THREAD

**Issue by TheRockettek** [TheRockettek/Sandwich-Daemon#8]
A lot of unnecessary and badly written code and logic is implemented within the code that need to be replaced. For example:

- `string([]bytes object)` should be replaced with `gotils.B2S([]bytes object)`.
- `sync.Map{}` should be used more often.
- Some places where we use a map instead of a slice is infact slower and should be replaced such as when checking for blacklisted events.
- Poorly written if statements that should prioritise code that would end first.
- The READY statement does not use a context.Background() with a timeout which in its current state would require a message to be sent to recognise a timeout on READY which does not have any negative consequences but bad design.

**Comment by Hamzsd** [comment]
Hello, @TheRockettek I would like to contribute to this project. I am interested to know which files or portion of code needs optimization?
